services:
  app:
    user: "www-data"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao-php-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - gestao_app_data:/var/www
    networks:
      - webserver

networks:
  webserver:
    external: true

volumes:
  gestao_app_data:
